
import { GoogleGenAI, Modality } from '@google/genai';

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY as string });

function getPlacementInstruction(category: string): string {
    switch(category) {
        case 'مصابيح سقف':
        case 'سبوتات':
            return 'The fixture should be installed on the ceiling.';
        case 'أباجورات':
            return 'The lamp should be placed on a suitable surface like a table or the floor.';
        case 'إضاءة خارجية':
            return 'The light should be placed on an exterior wall or in a garden setting.';
        default:
            return 'Place the fixture appropriately in the room.';
    }
}

export const placeProductInImage = async (
  roomImageBase64: string,
  roomImageMimeType: string,
  productImageBase64: string,
  productImageMimeType: string,
  prompt: string,
  category: string
): Promise<string> => {
    try {
        const placement = getPlacementInstruction(category);
        const fullPrompt = `
            You are an expert interior design visualizer. Your task is to realistically integrate a lighting product into a room photo.
            - Room photo is provided.
            - Lighting product photo is provided.
            - User instruction: "${prompt}"
            - Placement guideline based on category: "${placement}"
            Combine these elements to create a photorealistic image. Pay close attention to scale, perspective, lighting, and shadows to make the integration seamless.
        `;

        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash-image',
            contents: {
                parts: [
                    {
                        inlineData: {
                            data: roomImageBase64,
                            mimeType: roomImageMimeType,
                        },
                    },
                    {
                        inlineData: {
                            data: productImageBase64,
                            mimeType: productImageMimeType,
                        },
                    },
                    {
                        text: fullPrompt,
                    },
                ],
            },
            config: {
                responseModalities: [Modality.IMAGE],
            },
        });
        
        for (const part of response.candidates[0].content.parts) {
            if (part.inlineData) {
                const base64ImageBytes: string = part.inlineData.data;
                const mimeType: string = part.inlineData.mimeType;
                return `data:${mimeType};base64,${base64ImageBytes}`;
            }
        }

        throw new Error('No image was generated by the API.');

    } catch (error) {
        console.error("Error calling Gemini API:", error);
        throw new Error("Failed to generate image with Gemini API.");
    }
};
